version: '3.9'
services:

  2pdf-service:
    container_name: 2pdf-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./app:/usr/src/app
    command: tail -f /dev/null
